version: '3.9'

services:

  db:
    image: postgres:16-alpine
    container_name: moviedb
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kingdomain1!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: movie-reservation-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/moviedb
      DB_USERNAME: postgres
      DB_PASSWORD: Kingdomain1!
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
